### ISSUE TITLE
Error Message After Installing Package on Python 3.7.5 and Having MinGW on Path (OSError: [WinError 193] %1 is not a valid Win32 application and 'XRotor' object has no attribute '_lib')

### ISSUE THREAD

**Issue by marcosaantos** [DARcorporation/xrotor-python#2]
I have downloaded all the pre-requisites (Python and MinGW as gcc and fortran compiler), but still get problems in running the code, as is shown in the message below.Do you know what could be causing the error? I have Python 3.7.5 64-bit installed (I tried having its 32-bit version, but the XRotor package could not be downloaded with it).

C:\Users\msantos43\PycharmProjects\Test03\venv\Scripts\python.exe C:/Users/msantos43/PycharmProjects/Test03/Test03.py
Traceback (most recent call last):
  File "C:/Users/msantos43/PycharmProjects/Test03/Test03.py", line 2, in <module>
    xr=XRotor()
  File "C:\Users\msantos43\PycharmProjects\Test03\venv\lib\site-packages\xrotor\xrotor.py", line 55, in __init__
    self._lib = cdll.LoadLibrary(self._lib_path)
  File "C:\Users\msantos43\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\msantos43\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
Exception ignored in: <function XRotor.__del__ at 0x000001C6E2CC0A68>
Traceback (most recent call last):
  File "C:\Users\msantos43\PycharmProjects\Test03\venv\lib\site-packages\xrotor\xrotor.py", line 69, in __del__
    handle = self._lib._handle
AttributeError: 'XRotor' object has no attribute '_lib'

**Comment by KikeM** [comment]
Hi,

I am not the maintainer of this repository, but I run into a similar issue with another repository whose build process is similar to this one.

See my reply to issue #1, I think both of you have a similar problem. 

If the installation finished correctly, the library should be compiled, but it might not be where the code expects so. You might need to look for it and update [line 30 on `xrotor.py`](https://github.com/DARcorporation/xrotor-python/blob/9607e15925b44205e955bc63d53eacb1bd8b93cb/xrotor/xrotor.py#L30). 

Let me know how it goes!
